### PR TITLE
fix(platform): server:start with specified domain

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
Do not ignore the domain parameter if it's specified.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14095

### CODE REVIEW

**Comment by benoitf** [comment]
waiting target milestone of referenced issue

**Comment by sleshchenko** [comment]
@benoitf Do you think it makes sense to enable WIP bot for chectl repo?
That you would be able to approve if you're OK with changes, but it would not be merged without a milestone.

**Comment by benoitf** [comment]
@sleshchenko done

**Comment by ibuziuk** [comment]
@benoitf @sleshchenko are you plan to merge it before or after GA ?

**Comment by sleshchenko** [comment]
@ibuziuk Since the referenced issue is labeled with 7.0.0 milestone, I can merge it right now.

**Pull request merged**
