### PR TITLE
fix: Remove the process to check OIDC provider on server:deploy

### PR DESCRIPTION
**Pull request by ynqa**
### What does this PR do?

- Remove `--skip-oidc-provider-check` flag and its logic.

### What issues does this PR fix or reference?

https://github.com/eclipse-che/che/issues/23047

### How to test this PR?

```bash
%./bin/run server:deploy --skip-oidc-provider-check
Error: Nonexistent flag: --skip-oidc-provider-check
```

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by tolusha** [comment]
@ynqa 
Thank you for contribution. 
Could you sign your commits please to be able to merge the PR

https://github.com/che-incubator/chectl/pull/2902/checks?check_run_id=27833382813

**Comment by ynqa** [comment]
> Could you sign your commits please to be able to merge the PR

@tolusha Signed.

**Comment by tolusha** [comment]
Hello, @ynqa 
I remembered why I completed removed invocation `getEnsureOIDCProviderInstalledTask` from the codebase.
It causes more issues than benefits, since it is really hard to check if OIDC is configured in all kinds of clusters.
And usually I recommended to add `--skip-oidc-provider-check` flag.

**Comment by ynqa** [comment]
> It causes more issues than benefits, since it is really hard to check if OIDC is configured in all kinds of clusters.

@tolusha Yes, On EKS kube-apiserver is not exposed for users. The alternative of this pull request is to remove this flag and logic altogether because of avoidance of confusion.

**Comment by tolusha** [comment]
> The alternative of this pull request is to remove this flag and logic altogether for avoidance of confusion.

+1

**Comment by ynqa** [comment]
@tolusha Sure. I will remove them.

**Comment by ynqa** [comment]
@tolusha Removed

**Review by tolusha — APPROVED** [review]

**Pull request merged**
