### PR TITLE
feat: Add ppc64le support on travis-ci

### PR DESCRIPTION
**Pull request by Siddhesh-Ghadi**
Signed-off-by: Siddhesh Ghadi <Siddhesh.Ghadi@ibm.com>

### What does this PR do?

This PR will add support for ppc64le.

### What issues does this PR fix or reference?

### CODE REVIEW

**Comment by flacatus** [comment]
Hello @Siddhesh-Ghadi ! Thank you very much for your contribution. I want to remark something: if you put `linux-ppc64le` arch in jobs, travis will create 2 releases instead of two and that is an error. Please add `linux-ppc64le` in `TARGTETS` variable like `linux-s390x`.

**Comment by Siddhesh-Ghadi** [comment]
Are you suggesting to remove
https://github.com/che-incubator/chectl/blob/2df364c35f2e3d3b35779627bdab373030f29b4a/.travis.yml#L4-L5
And add `linux-ppc64le` here
https://github.com/che-incubator/chectl/blob/2df364c35f2e3d3b35779627bdab373030f29b4a/.travis.yml#L34
Or is it just add `linux-ppc64le` in `TARGETS` variable without removing `os:linux & arch:ppc64le` tag? @flacatus

**Comment by flacatus** [comment]
> Are you suggesting to remove
> https://github.com/che-incubator/chectl/blob/2df364c35f2e3d3b35779627bdab373030f29b4a/.travis.yml#L4-L5
> 
> 
> And add `linux-ppc64le` here
> https://github.com/che-incubator/chectl/blob/2df364c35f2e3d3b35779627bdab373030f29b4a/.travis.yml#L34
> 
> 
> Or is it just add `linux-ppc64le` in `TARGETS` variable without removing `os:linux & arch:ppc64le` tag? @flacatus

**Comment by Siddhesh-Ghadi** [comment]
Please check. @flacatus

**Pull request merged**
