### PR TITLE
feat: reorder if blocks in platform and installer...

### PR DESCRIPTION
**Pull request by nickboldt**
reorder if blocks in platform and installer so we can more easily exclude them when converting code into crwctl version

Change-Id: I4f262d9baf1b3e129c646f958ebb137a3916276a
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
Help! Why are tests failing for this no-op change?

**Comment by tolusha** [comment]
@nickboldt 
I will check ...

**Comment by flacatus** [comment]
[test]

**Comment by tolusha** [comment]
closed in favor of https://github.com/che-incubator/chectl/pull/572

**Pull request closed without merging**
