### PR TITLE
chore: CRW-4820 bump to node 18...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore: [CRW-4820](https://issues.redhat.com//browse/CRW-4820) bump to node 18 requirement

Change-Id: If63b174ae61f8fef473c35d5ada426bc963b6359
Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit message above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by tolusha** [comment]
Depends on https://github.com/che-incubator/chectl/pull/2731

**Comment by SDawley** [comment]
If everyone seems to be convinced that these are just test failures, can we merge?

**Comment by tolusha** [comment]
Unfortunately we can't merge since won't be able to run tests against OpenShift CI.
The idea is to have Node 18 here [1]

[1] https://github.com/che-incubator/chectl/blob/main/.ci/openshift-ci/Dockerfile

**Comment by nickboldt** [comment]
Using new dockerfile I was able to build w/ node 18:

```
FROM registry.access.redhat.com/ubi9/nodejs-18:1
USER 0
RUN dnf install -y -q --allowerasing --nobest nodejs-devel nodejs-libs \
  # already installed or installed as deps:
  openssl openssl-devel ca-certificates make cmake cpp gcc gcc-c++ zlib zlib-devel brotli brotli-devel python3 nodejs-packaging && \
  dnf update -y && dnf clean all && \
  npm install -g yarn@1.22 npm@9 && \
  echo -n "node version: "; node -v; \
  echo -n "npm  version: "; npm -v; \
  echo -n "yarn version: "; yarn -v

COPY . /opt/app-root/src
RUN yarn && yarn pack && yarn test
```

```
podman build -f .ci/openshift-ci/Dockerfile -t openshift-ci .
podman run -it --rm --entrypoint /bin/bash --user root openshift-ci
```

then in the container: 

```
bash-5.1# ls -la /opt/app-root/src/*gz
-rw-r--r-- 1 root root 136908 Aug 30 16:28 /opt/app-root/src/chectl-v0.0.2.tgz

bash-5.1# cd /opt/app-root/src/; ./bin/run --version
chectl/0.0.2 linux-x64 node-v18.16.1

bash-5.1# cd /opt/app-root/src/; ./bin/run server:update --help
Update Eclipse Che server.

USAGE
  $ chectl server:update
...
```

**Pull request merged**
