### PR TITLE
chore: enable native user mode if devworkspace engine is enabled

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

### What does this PR do?
Enable native user mode if devworkspace engine is enabled

### Screenshot/screencast of this PR

```
  ✔ Show important messages
    ✔ Eclipse Che 7.41.0-SNAPSHOT has been successfully deployed.
    ✔ Documentation             : https://www.eclipse.org/che/docs/
    ✔ -------------------------------------------------------------------------------
    ✔ Users Dashboard           : https://192.168.99.100.nip.io
    ✔ Admin user login          : "admin:admin". NOTE: must change after first login.
    ✔ -------------------------------------------------------------------------------
    ✔ Plug-in Registry          : https://192.168.99.100.nip.io/plugin-registry/v3/
    ✔ Devfile Registry          : https://192.168.99.100.nip.io/devfile-registry/
    ✔ -------------------------------------------------------------------------------
    ✔ Dex user credentials      : che@eclipse.org:admin
    ✔ Dex user credentials      : user1@che:password
    ✔ Dex user credentials      : user2@che:password
    ✔ Dex user credentials      : user3@che:password
    ✔ Dex user credentials      : user4@che:password
    ✔ Dex user credentials      : user5@che:password
    ✔ -------------------------------------------------------------------------------
Command server:deploy has completed successfully in 08:26.
```    

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20853
https://github.com/eclipse/che/issues/20779

### How to test this PR?

`./run server:deploy --platform minikube --workspace-engine dev-workspace`

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by sparkoo** [comment]
I've tested with my che-operator image https://github.com/eclipse-che/che-operator/pull/1185 and works fine.

One issue here is, we no longer need the warning prompt that there is privilege escalation (https://github.com/che-incubator/chectl/blob/main/src/commands/server/deploy.ts#L343). I've fixed that in previous PR (https://github.com/che-incubator/chectl/pull/1864/files#diff-0c92bfdc017a79faa86cda8534f6cd10e6aa230c187d56f76e01a3df5a065b41R342), but it's not working here. I guess you set the value after this check.

**Comment by sparkoo** [comment]
next we should consider to include here printing the credentials of precreated users, because people won't know how to login to Che, which is an issue when it is the default https://github.com/eclipse/che/issues/20779

**Comment by tolusha** [comment]
@sparkoo 
Updated

**Comment by sparkoo** [comment]
> @sparkoo Updated

nice. I've tested that and works fine

**Review by sparkoo — APPROVED** [review]

**Review by AndrienkoAleksandr — APPROVED** [review]

**Pull request merged**
