### PR TITLE
Release version 7.16.0

### PR DESCRIPTION
**Pull request by mkuznyetsov**

### CODE REVIEW

**Comment by mkuznyetsov** [comment]
[test]

**Comment by mkuznyetsov** [comment]
[test]

**Comment by flacatus** [comment]
[test]

**Comment by flacatus** [comment]
[test]

**Comment by mkuznyetsov** [comment]
[test]

**Comment by mkuznyetsov** [comment]
closing this PR and reopening a new one

**Comment by flacatus** [comment]
[test]

**Comment by mkuznyetsov** [comment]
update tested on minishift

**Pull request merged**
