### PR TITLE
ci: Use NodeJS 16

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

### What does this PR do?
* Use NodeJS 16
* Unify PRs checks

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/21075

### How to test this PR?

N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by benoitf** [comment]
probably https://github.com/che-incubator/chectl/blob/1f6cc7181d806ae8dbfcb7b56a80d1531016ffbc/package.json#L54 and https://github.com/che-incubator/chectl/blob/1f6cc7181d806ae8dbfcb7b56a80d1531016ffbc/package.json#L76 could be bumped as well

**Review by benoitf — APPROVED** [review]
approving overall changes, but it seems there are still compilation failures

**Comment by benoitf** [comment]
it seems openshift ci is failing due to

```
[1/5] Validating package.json...
error chectl@0.0.2: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "12.22.9"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by benoitf** [comment]
https://github.com/che-incubator/chectl/blob/main/.ci/openshift-ci/Dockerfile#L17

**Comment by tolusha** [comment]
I've changed it 
https://github.com/che-incubator/chectl/pull/1986/files#diff-6704820b78e3aea8581dff31b66a527b85fc1e2635264f0c6961acb16529ff24
It must be another reason

**Comment by tolusha** [comment]
Fixed by updating NodeJs version in the main branch
https://github.com/che-incubator/chectl/pull/1988

**Pull request merged**
