### PR TITLE
feat: reorder if blocks in platform and installer and use correct selectors

### PR DESCRIPTION
**Pull request by tolusha**
reorder if blocks in platform and installer so we can more easily exclude them when converting code into crwctl version

/cc @nickboldt

### CODE REVIEW

**Comment by tolusha** [comment]
@nickboldt 
I suspect your working copy is outdated.

**Comment by nickboldt** [comment]
well, that's BETTER but still one test failing.

**Comment by nickboldt** [comment]
[e2e_tess]

**Comment by nickboldt** [comment]
[test]

**Pull request merged**
