### PR TITLE
feat: reorder if blocks in platform and installer so we can more easily exclude them from crwctl

### PR DESCRIPTION
**Pull request by nickboldt**
reorder if blocks in platform and installer so we can more easily exclude them when converting code into crwctl version

Change-Id: I4f262d9baf1b3e129c646f958ebb137a3916276a
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by tolusha** [comment]
[test]

**Comment by tolusha** [comment]
@nickboldt 
tests failed.

**Comment by nickboldt** [comment]
Test failed because:

```
/bin/bash: .ci/cico_chectl_prcheck.sh: No such file or directory
```

**Comment by nickboldt** [comment]
resubmitted as #571 against master branch so we can verify the tests work :D

**Pull request merged**
