### PR TITLE
Add crc as a platform that will install with openshift oauth

### PR DESCRIPTION
**Pull request by tomgeorge**
Signed-off-by: Tom George <tg82490@gmail.com>

### What does this PR do?

Allows you to install che with OpenShift OAuth enabled on crc

### What issues does this PR fix or reference?
eclipse/che#15108

### CODE REVIEW

**Comment by sleshchenko** [comment]
commit message seems does not suite semantic rules. It could be something like:

> fix: Add crc as a platform that supports OpenShift OAuth

**Comment by ibuziuk** [comment]
@tomgeorge commit message naming convention applied for chectl https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by benoitf** [comment]
approving but still need to fix commit message

**Comment by tomgeorge** [comment]
updated the commit message

**Comment by tomgeorge** [comment]
please note I opened a new PR for the backporting https://github.com/che-incubator/chectl/pull/410

**Comment by benoitf** [comment]
@tomgeorge you have rights to merge ?

**Comment by tomgeorge** [comment]
No, I don't

**Comment by benoitf** [comment]
@tomgeorge you should have received an invitation

**Comment by tomgeorge** [comment]
thanks!

**Pull request merged**
