### PR TITLE
feat: Remove the explicit DWCO (un)installation steps.

### PR DESCRIPTION
**Pull request by metlos**
### What does this PR do?
Make sure that DWCO related objects are deleted during che-operator uninstallation instead of devworkspace uninstallation.

This only makes sense when the referenced issues are merged.

### What issues does this PR fix or reference?
eclipse/che#19402
eclipse/che#19847

### How to test this PR?
1. Install Che using the operator
2. Delete the Che installation using `chectl server:delete`
3. Make sure it works OK
    ```
    oc get clusterroles | grep devworkspace-che
    oc get roles -n eclipse-che | grep devworkspace-che
    oc get rolebindings -n eclipse-che | grep devworkspace-che
    oc get clusterrolebindings -n eclipse-che | grep devworkspace-che
    ```
4. Install Che using the operator again
5. Enable devworkspaces
    ```
    oc patch checluster eclipse-che -n eclipse-che --type=json -p '[{"op": "replace", "path": "/spec/devWorkspace/enable", "value": true}]'
    ```
6. Delete the Che installation using `chectl server:delete` again
7. Make sure there are no remnants of DWCO using the step 3

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Comment by mmorhun** [comment]
Rebased

**Comment by mmorhun** [comment]
I've investigated why the `e2e update tests` tests fails and the problem is not related to the changes in this PR.

**Pull request merged**
