### PR TITLE
fix: Fix catalog yaml argument

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
1. Fix catalog source yaml argument for olm installer. 
2. Fix timeout installation error, when install plan installs longer than 30 sec. It's reproducible with cluster bot on first installation. Second installation is much faster and bug is not reproducible. Fix important for CRW.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18105

### How to test this PR?
**Test fix timeout error:**
1. Request cluster using bot.
2. Install Che first time:

```bash
$ ./bin/run server:start -n che -p openshift -m
```
This first installation could fail. With this fix it should not.

**Test catalogsource yaml argument:**
1. Create file with custom catalog source yaml:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: eclipse-che-preview-openshift
  namespace: che
spec:
  sourceType: grpc
  image: quay.io/aandriienko/eclipse-che-openshift-opm-catalog:preview
  updateStrategy:
    registryPoll:
      interval: 5m
```
2. Install Che on the Openshift cluster:

```bash
$ ./bin/run server:start -n che \
-p openshift \
-m \
--catalog-source-yaml "/home/user/projects/chectl/catalogSource.yaml" \
--package-manifest-name "eclipse-che-preview-openshift" \
--olm-channel "nightly" \
--installer olm
```

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Comment by tolusha** [comment]
@AndrienkoAleksandr 
pls ignore helm test
```
[11:03:04] → Command failed with exit code 1: helm dependencies update --skip-refresh /home/runner/.cache/chectl/templates/kubernetes/helm/che/
    Error: no cached repository for helm-manager-1067d9c6027b8c3f27b49e40521d64be96ea412858d8e45064fa44afd3966ddc found. (try 'helm repo update'): open /home/runner/.cache/helm/repository/helm-manager-1067d9c6027b8c3f27b49e40521d64be96ea412858d8e45064fa44afd3966ddc-index.yaml: no such file or directory
```

**Comment by AndrienkoAleksandr** [comment]
> pls ignore helm test

I launched this test locally - it's works fine... I think something wrong with this test on the ci.

**Review by mmorhun — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
Launched minishift e2e tests locally - passed.

**Pull request merged**
