### PR TITLE
fix: Fix minishift server:start test case

### PR DESCRIPTION
**Pull request by flacatus**
Signed-off-by: flacatus <flacatus@redhat.com>

### What does this PR do?
Sometimes the jobs crash with the next error:
`Timeout - Async callback was not invoked within the 600000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 600000ms timeout specified by jest.setTimeout.Error: `

### What issues does this PR fix or reference?
Execute `server:start` test case using execa library.

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
I guess pull request description should be changed corresponding to changes in the pr.

**Comment by flacatus** [comment]
> I guess pull request description should be changed corresponding to changes in the pr.

yes, after finish the changes I'll change the description.

**Comment by flacatus** [comment]
[test]

**Comment by flacatus** [comment]
I'll pass 2 times the tests to be 100% sure will work

**Comment by flacatus** [comment]
[test]

**Comment by flacatus** [comment]
[test]

**Comment by flacatus** [comment]
[test]

**Comment by flacatus** [comment]
[test]

**Comment by flacatus** [comment]
[test]

**Comment by flacatus** [comment]
[test]

**Comment by flacatus** [comment]
[test]

**Comment by flacatus** [comment]
[test]

**Comment by flacatus** [comment]
[test]

**Pull request merged**
