### PR TITLE
feat: Add s390x Support for Travis

### PR DESCRIPTION
**Pull request by aditijadhav38**
### What does this PR do?
This PR will add support for s390x.

### CODE REVIEW

**Comment by tolusha** [comment]
@aditijadhav38 
Thank you for contribution.
Please, have a look https://github.com/che-incubator/chectl/pull/575/checks?check_run_id=503292027

**Comment by aditijadhav38** [comment]
@tolusha All the checks are now passing. 
Please check https://github.com/che-incubator/chectl/pull/575/checks?check_run_id=504985779

**Comment by tolusha** [comment]
/cc
@rhopp @flacatus

**Comment by flacatus** [comment]
@tolusha @aditijadhav38 approved from my side.

**Comment by aditijadhav38** [comment]
@tolusha @flacatus Could you please let me know when will be the next release and is there any plan to publish s390x binaries same way like Intel through travis.

**Comment by tolusha** [comment]
There is the new release, but without s390x binaries.
https://github.com/che-incubator/chectl/releases/tag/20200313144956

@benoitf @flacatus 
Do we know how to publish s390x binaries? Is there release script somewhere?

**Comment by aditijadhav38** [comment]
> @tolusha @aditijadhav38 approved from my side.

Thank you so much for the positive response.

**Comment by tolusha** [comment]
@aditijadhav38 
here is
https://github.com/che-incubator/chectl/releases/tag/20200313144056

**Pull request merged**
