### PR TITLE
fix: set cheClusterRoles to correct clusterrole name

### PR DESCRIPTION
**Pull request by sparkoo**
Signed-off-by: Michal Vala <mvala@redhat.com>

### What does this PR do?
after https://github.com/eclipse/che-operator/pull/543, we need to set correct namespace-editor clusterrole into CheCluster CR.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/18400

### How to test this PR?

1. deploy with operator
1. check that cheClusterRoles is set to valid clusterrole name

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by flacatus** [comment]
Please ignore Openshift CI jobs and helm tests

**Review by tolusha — APPROVED** [review]
It should be merged once [1] is merged  and after updating dependencies. 

[1] https://github.com/eclipse/che-operator/pull/543

**Review by AndrienkoAleksandr — APPROVED** [review]

**Review by mmorhun — APPROVED** [review]

**Review by tolusha — CHANGES_REQUESTED** [review]
https://github.com/eclipse/che-operator/pull/543 creates a new CRB, we have to make sure that all of them removed on `server:delete` command

**Comment by sparkoo** [comment]
> [eclipse/che-operator#543](https://github.com/eclipse/che-operator/pull/543) creates a new CRB, we have to make sure that all of them removed on `server:delete` command

Created separate issue https://github.com/eclipse/che/issues/18501

**Review by tolusha — APPROVED** [review]
It should be merged once [1] is merged and after updating dependencies.
[1] eclipse/che-operator#543

**Comment by tolusha** [comment]
`Minishift E2E / Operator installer ` tested locally.

**Pull request merged**
