### PR TITLE
fix(helm): fix deploying che with helm installer when self-signed-cert is specified

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
Fixes deploying Che with helm installer when self-signed-cert is specified

### What issues does this PR fix or reference?
It's related to https://github.com/eclipse/che/issues/14035
It depends on https://github.com/eclipse/che/pull/14176

### CODE REVIEW

**Comment by sleshchenko** [comment]
@l0rd @slemeur Maybe you would like set `7.0.0` milestone to this and che related PR otherwise, it won't be possible to deploy Che with chectl (helm as installer) or bare helm if self-signed-cert is configured.

**Comment by l0rd** [comment]
I am +1 to include this in milestone `7.0.0`

**Comment by l0rd** [comment]
cc @slemeur @benoitf @rhopp

**Comment by benoitf** [comment]
@sleshchenko could you please fix compilation issue ?

**Pull request merged**
