### PR TITLE
fix(openshift/minishift): Do ask for domain parameter for openshift/minishift platforms

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
Do ask for domain parameter for openshift/minishift platforms

This PR is under WIP phase because it is supposed to be merged in 7.1.0

### What issues does this PR fix or reference?
N/A

### CODE REVIEW

**Comment by benoitf** [comment]
hello, what is related issue ? to know if it's for `7.0.0` or `7.1.0` ?

**Comment by sleshchenko** [comment]
@benoitf It's a tiny improvement I discovered during using chectl.
I have not even created an issue because it would be bigger than the fix itself.
Can you set milestone directly to PR or I should create an issue?
I'm OK with `7.1` since it is not blocker, but it should not break anything - I believe `7.0` should be fine as well.

**Comment by l0rd** [comment]
@sleshchenko why are you removing setting the domain automatically on minishift?

**Comment by sleshchenko** [comment]
@l0rd Because it is unused on OpenShift platform. 
OS infra assign host automatically for Routes.
For K8s it's needed because there Che Server defines host based rules for Ingresses.

**Comment by l0rd** [comment]
@sleshchenko ok makes sense

**Pull request merged**
