### PR TITLE
feat(minishift-addon): Embed minishift addon

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Embed minishift addon into chectl

### What issues does this PR fix or reference?
Fix https://github.com/eclipse/che/issues/13889
Fix https://github.com/eclipse/che/issues/14137
Fix https://github.com/eclipse/che/issues/14136

example with an old version of minishift:
```
$ minishift version
minishift v1.34.0+f5db7cb
```

```
$ chectl server:start --installer=minishift-addon --platform=minishift
  ✔ ✈️  Minishift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if minishift is installed...done.
    ✔ Verify if minishift is running...done.
    ✔ Retrieving minishift IP and domain for routes URLs...192.168.99.131.nip.io.
  ✔ 🏃‍  Running the Che minishift-addon
    ✔ Check minishift version...done.
    ✔ Check logged...done.
    ✔ Copying addon resources...done.
    ✔ Check che addon is available...done.
    ✔ Apply Che addon...done.
  ✔ ✅  Post installation checklist
    ✔ Che pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Retrieving Che Server URL...http://che-che.192.168.99.131.nip.io
    ✔ Che status check
Command server:start has completed successfully.
```

And plugin registry is correct
```
$ oc get dc/che -o json | grep plugin
   "value": "https://che-plugin-registry.openshift.io/v3"
```

### CODE REVIEW

**Comment by l0rd** [comment]
@benoitf I see that we are not deploying the registries when the installer is the minishift-addon. That makes sense because the minishift addon doesn't deploy them. But that's still an issue: the version of the registries on osio is an outdated one. We need to update the registries on openshift.io. It should be straightforward for the devfile registries, not sure for the plugin registry cc @ibuziuk

**Comment by benoitf** [comment]
@l0rd yes https://github.com/eclipse/che/issues/14138 and https://github.com/openshiftio/saas-openshiftio/pull/1323

**Comment by ibuziuk** [comment]
> It should be straightforward for the devfile registries, not sure for the plugin registry cc @ibuziuk
Looks like nothing should be broken, so I approved the PR with promotion to prod. It is absolutely needed I'm ok to promote it to production now

**Comment by l0rd** [comment]
@benoitf @ibuziuk fantastic. devfile registry should be updated as well.

**Comment by ibuziuk** [comment]
both plugin and devfile registries have been updated on prod

**Pull request merged**
